name: Frontend production

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      root: ./frontend
      dist: ./frontend/dist
      infrastructure: ./frontend/infrastructure

    steps:
      - uses: actions/checkout@v2

      # NodeJS installing
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
        working-directory: ${{env.root}}

      # Building of the bundle
      - run: npm run production:build
        working-directory: ${{env.root}}

      # For results checking
      - run: ls -la
        working-directory: ${{env.root}}
      - run: ls -la
        working-directory: ${{env.dist}}

      # Uploading
      - run: node activate.js ${{secrets.activationData}}
        working-directory: ${{env.infrastructure}}